/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import db.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Tikkun
 */
public class frmChangePin extends javax.swing.JFrame {

    private String username;

    /**
     * Creates new form frmChangePin
     */
    public frmChangePin() {
        initComponents();
    }

    public frmChangePin(String username) {
        this.username = username;
        initComponents();
        lblWelcome.setText("Hello " + username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblConfirmPin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtConfirmPin = new javax.swing.JTextField();
        txtNewPin = new javax.swing.JTextField();
        btnChangePin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        lblClose.setForeground(new java.awt.Color(0, 0, 0));
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, -1));

        lblConfirmPin.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        lblConfirmPin.setForeground(new java.awt.Color(0, 0, 0));
        lblConfirmPin.setText("Confirm Pin");
        jPanel1.add(lblConfirmPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Change Pin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 0));
        lblWelcome.setText("Hello");
        jPanel1.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("New Pin");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 120, -1));

        txtConfirmPin.setBackground(new java.awt.Color(102, 102, 102));
        txtConfirmPin.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        txtConfirmPin.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtConfirmPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 210, -1));

        txtNewPin.setBackground(new java.awt.Color(102, 102, 102));
        txtNewPin.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        txtNewPin.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtNewPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 210, -1));

        btnChangePin.setBackground(new java.awt.Color(153, 153, 255));
        btnChangePin.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnChangePin.setForeground(new java.awt.Color(0, 0, 0));
        btnChangePin.setText("Change Pin");
        btnChangePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePinActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/skin3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 907, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm If You Want To Exit", "ATM Machine", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frmMain frmMain = new frmMain(username);
        frmMain.show();
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnChangePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePinActionPerformed
        // TODO add your handling code here:
        String newPin = txtNewPin.getText().trim();
        String confirmPin = txtConfirmPin.getText().trim();

        if (newPin.isEmpty() || confirmPin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the new PIN and confirm it.", "Input Error", JOptionPane.ERROR_MESSAGE);
            clearText();
        }else if (!isValidPin(newPin)) {
            JOptionPane.showMessageDialog(this, "PIN must be a number between 4 and 6 digits.", "Invalid PIN", JOptionPane.ERROR_MESSAGE);
            clearText();
        }else if (!newPin.equals(confirmPin)) {
            JOptionPane.showMessageDialog(this, "The PINs do not match. Please try again.", "Input Error", JOptionPane.ERROR_MESSAGE);
            clearText();
        }else{
            changePin(newPin);
            clearText();
        }
    }//GEN-LAST:event_btnChangePinActionPerformed

    private boolean isValidPin(String pin) {
        if (pin.length() < 4 || pin.length() > 6) {
            return false;
        }
        try {
            Integer.parseInt(pin);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }
    
    private void changePin(String newPin) {
        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql = "UPDATE users SET pin = ? WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, newPin);
            pstmt.setString(2, username);

            int rowsUpdated = pstmt.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "PIN changed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to change PIN. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred while changing the PIN. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void clearText(){
        txtNewPin.setText("");
        txtConfirmPin.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChangePin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangePin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfirmPin;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtConfirmPin;
    private javax.swing.JTextField txtNewPin;
    // End of variables declaration//GEN-END:variables
}
