/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import db.DatabaseConnection;

/**
 *
 * @author Tikkun
 */
public class frmWithdraw extends javax.swing.JFrame {

    private String username;

    /**
     * Creates new form frmWithdraw
     */
    public frmWithdraw() {
        initComponents();
    }

    public frmWithdraw(String username) {
        this.username = username; // Store the passed username
        initComponents();
        updateBalanceLabel(); // Update balance label when form initializes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnWithdraw200 = new javax.swing.JButton();
        btnWithdraw1000 = new javax.swing.JButton();
        btnWithdraw100 = new javax.swing.JButton();
        btnWithdraw50 = new javax.swing.JButton();
        btnWithdraw10000 = new javax.swing.JButton();
        btnWithdraw5000 = new javax.swing.JButton();
        btnWithdraw500 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, -1));

        lblBalance.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 220, 30));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 580, 120, -1));

        btnWithdraw200.setBackground(new java.awt.Color(153, 153, 255));
        btnWithdraw200.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnWithdraw200.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdraw200.setText("R200");
        btnWithdraw200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw200ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWithdraw200, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 120, -1));

        btnWithdraw1000.setBackground(new java.awt.Color(153, 153, 255));
        btnWithdraw1000.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnWithdraw1000.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdraw1000.setText("R1 000");
        btnWithdraw1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw1000ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWithdraw1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 550, 120, -1));

        btnWithdraw100.setBackground(new java.awt.Color(153, 153, 255));
        btnWithdraw100.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnWithdraw100.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdraw100.setText("R100");
        btnWithdraw100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw100ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWithdraw100, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 520, 120, -1));

        btnWithdraw50.setBackground(new java.awt.Color(153, 153, 255));
        btnWithdraw50.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnWithdraw50.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdraw50.setText("R50");
        btnWithdraw50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw50ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWithdraw50, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 490, 120, -1));

        btnWithdraw10000.setBackground(new java.awt.Color(153, 153, 255));
        btnWithdraw10000.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnWithdraw10000.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdraw10000.setText("R10 000");
        btnWithdraw10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw10000ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWithdraw10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 120, -1));

        btnWithdraw5000.setBackground(new java.awt.Color(153, 153, 255));
        btnWithdraw5000.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnWithdraw5000.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdraw5000.setText("R5 000");
        btnWithdraw5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw5000ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWithdraw5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 120, -1));

        btnWithdraw500.setBackground(new java.awt.Color(153, 153, 255));
        btnWithdraw500.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnWithdraw500.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdraw500.setText("R500");
        btnWithdraw500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw500ActionPerformed(evt);
            }
        });
        jPanel1.add(btnWithdraw500, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 120, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Withdraw");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/skin3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm If You Want To Exit", "ATM Machine", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frmMain frmMain = new frmMain(username);
        frmMain.show();
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnWithdraw50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdraw50ActionPerformed
        // TODO add your handling code here:
        withdrawAmount(50);
    }//GEN-LAST:event_btnWithdraw50ActionPerformed

    private void btnWithdraw200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdraw200ActionPerformed
        // TODO add your handling code here:
        withdrawAmount(200);
    }//GEN-LAST:event_btnWithdraw200ActionPerformed

    private void btnWithdraw100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdraw100ActionPerformed
        // TODO add your handling code here:
        withdrawAmount(100);
    }//GEN-LAST:event_btnWithdraw100ActionPerformed

    private void btnWithdraw500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdraw500ActionPerformed
        // TODO add your handling code here:
        withdrawAmount(500);
    }//GEN-LAST:event_btnWithdraw500ActionPerformed

    private void btnWithdraw1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdraw1000ActionPerformed
        // TODO add your handling code here:
        withdrawAmount(1000);
    }//GEN-LAST:event_btnWithdraw1000ActionPerformed

    private void btnWithdraw5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdraw5000ActionPerformed
        // TODO add your handling code here:
        withdrawAmount(5000);
    }//GEN-LAST:event_btnWithdraw5000ActionPerformed

    private void btnWithdraw10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdraw10000ActionPerformed
        // TODO add your handling code here:
        withdrawAmount(10000);
    }//GEN-LAST:event_btnWithdraw10000ActionPerformed

    private void withdrawAmount(double amount) {
        double currentBalance = getCurrentBalance();

        if (currentBalance >= amount) {
            try (Connection conn = DatabaseConnection.getConnection()) {
                String sql = "UPDATE users SET balance = balance - ? WHERE username = ? AND balance >= ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setDouble(1, amount);
                pstmt.setString(2, username); // Use the stored username
                pstmt.setDouble(3, amount); // Check if sufficient balance

                int rowsUpdated = pstmt.executeUpdate();
                if (rowsUpdated > 0) {
                    updateBalanceLabel(); // Update balance label after successful withdrawal
                    JOptionPane.showMessageDialog(this, "Successfully withdrew R" + amount, "Withdrawal Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Insufficient balance. Please try a lower amount.", "Withdrawal Failed", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Insufficient balance. Please try a lower amount.", "Withdrawal Failed", JOptionPane.ERROR_MESSAGE);
        }
    }

    private double getCurrentBalance() {
        double balance = 0.0;
        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql = "SELECT balance FROM users WHERE username = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);

            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                balance = rs.getDouble("balance");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return balance;
    }

    private void updateBalanceLabel() {
        double balance = getCurrentBalance();
        lblBalance.setText("Current Balance: R" + balance);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmWithdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnWithdraw100;
    private javax.swing.JButton btnWithdraw1000;
    private javax.swing.JButton btnWithdraw10000;
    private javax.swing.JButton btnWithdraw200;
    private javax.swing.JButton btnWithdraw50;
    private javax.swing.JButton btnWithdraw500;
    private javax.swing.JButton btnWithdraw5000;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBalance;
    // End of variables declaration//GEN-END:variables
}
